# Docker安装Server

version: '3'
services:
  hbiba-esp32-server:
    image: ghcr.io/xinnan-tech/xiaozhi-esp32-server:server_latest
    container_name: hbiba-esp32-server
    restart: always
    security_opt:
      - seccomp:unconfined
    environment:
      - TZ=UTC
    ports:
      # ws服务端
      - "8000:8000"
      # http服务的端口，用于简单OTA接口(单服务部署)，以及视觉分析接口
      - "8003:8003"
    volumes:
      # 配置文件目录
      - ./data:/opt/xiaozhi-esp32-server/data
      # Fonctions personnalisées (ex: robot_control.py)
      - ./plugins_func:/opt/xiaozhi-esp32-server/plugins_func